CREATE DATABASE QuanLyNguoiDungDB;

USE QuanLyNguoiDungDB;

CREATE TABLE NguoiDung (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Email NVARCHAR(50) NOT NULL,
    MatKhau NVARCHAR(50) NOT NULL,
    HoTen NVARCHAR(50) NOT NULL,
    MSSV NVARCHAR(20) NOT NULL
);
